site_name: "beset"
docs_dir: doc
site_dir: doc-site
theme:
  name: readthedocs

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_full_path: false
            show_source: false
            members_order: source
