[tool.poetry]
name = "beset"
version = "0.1.0"
description = "A Python library for handling intervals"
authors = ["ExOriente <oosten@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
