env_list = ["lint", "3.10", "3.11", "3.12", "3.13", "3.14"]

[env_run_base]
description = "run the test suite with pytest"
deps = [
    "pytest>=9",
]
commands = [["pytest", { replace = "posargs", default = ["test"], extend = true }]]

[env.lint]
description = "run linters"
base_python = "python3.14"
package = "skip"
dependency_groups = ["dev"]
commands = [
    ["ruff", "check", { replace = "posargs", default = ["."], extend = true }],
    ["mypy", { replace = "posargs", default = ["src", "test"], extend = true }],
    ["ty", "check", { replace = "posargs", default = ["src", "test"], extend = true }],
    ["pyright", { replace = "posargs", default = ["src", "test"], extend = true }],
    ["pyrefly", "check", { replace = "posargs", default = ["src", "test"], extend = true }],
]
